### ISSUE TITLE
PHP 7.1 RC1 compile fail.

### ISSUE THREAD

**Issue by designinlife** [msgpack/msgpack-php#100]
msgpack-php-master/msgpack.c: In function ‘ps_srlzr_decode_msgpack’:
msgpack-php-master/msgpack.c:160: error: storage size of ‘var_hash’ isn’t known
msgpack-php-master/msgpack.c: In function ‘php_msgpack_unserialize’:
msgpack-php-master/msgpack.c:210: error: storage size of ‘var_hash’ isn’t known
make: **\* [msgpack.lo] Error 1

**Comment by remicollet** [comment]
same issue (RC2)

**Comment by remicollet** [comment]
Related to http://git.php.net/?p=php-src.git;a=commitdiff;h=09f7bb2082067baab56fe0f04a6531beef253d95

**Comment by remicollet** [comment]
@laruence what fo you think of

```
diff --git a/msgpack_unpack.h b/msgpack_unpack.h
index 5dc9524..ffe41b6 100644
--- a/msgpack_unpack.h
+++ b/msgpack_unpack.h
@@ -16,7 +16,13 @@ typedef enum
     MSGPACK_UNPACK_PARSE_ERROR = -1,
 } msgpack_unpack_return;
 
-typedef struct php_unserialize_data msgpack_unserialize_data_t;
+typedef struct _msgpack_unserialize_data {
+       void *first;
+       void *last;
+       void *first_dtor;
+       void *last_dtor;
+       HashTable *allowed_classes;
+} msgpack_unserialize_data_t;
 
 typedef struct {
     zval *retval;
```

IIUC, using php_unserialize_data was only a shortcut, but this is not used to call PHP API, everything in implement in this extension, right ?

**Comment by sodabrew** [comment]
Subscribe

**Comment by michael-grunder** [comment]
The proposed fix by @remicollet works, although I have only verified that php will now compile again and msgpack seems fine :smiley:

**Comment by laruence** [comment]
if all tests passes,  I think it's okey to merge this, thanks & sorry for late response :<

**Comment by zhangjunlei26** [comment]
php 7.1.0.RC6
msgpack-php/msgpack.c: In function ‘ps_srlzr_decode_msgpack’:
msgpack-php/msgpack.c:160:29: error: storage size of ‘var_hash’ isn’t known
  msgpack_unserialize_data_t var_hash;
                             ^~~~~~~~
msgpack-php/msgpack.c: In function ‘php_msgpack_unserialize’:
msgpack-php/msgpack.c:210:29: error: storage size of ‘var_hash’ isn’t known
  msgpack_unserialize_data_t var_hash;
                             ^~~~~~~~
Makefile:193: recipe for target 'msgpack.lo' failed
make: *** [msgpack.lo] Error 1

**Comment by RochesterinNYC** [comment]
Hi we're coming across this as well when we're trying to compile the latest released `PHP 7.1.0` with `msgpack 2.0.1`:

```
========================================================================
     var_entries *var_hash = var_hashx->first;
                                      ^
/tmp/x86_64-linux-gnu/ports/msgpack/2.0.1/msgpack-2.0.1/msgpack_unpack.c:298:25: error: dereferencing pointer to incomplete type
     var_hash = var_hashx->first_dtor;
                         ^
make: *** [msgpack_unpack.lo] Error 1
make: *** Waiting for unfinished jobs....
/tmp/x86_64-linux-gnu/ports/msgpack/2.0.1/msgpack-2.0.1/msgpack.c: In function 'ps_srlzr_decode_msgpack':
/tmp/x86_64-linux-gnu/ports/msgpack/2.0.1/msgpack-2.0.1/msgpack.c:160:29: error: storage size of 'var_hash' isn't known
  msgpack_unserialize_data_t var_hash;
                             ^
/tmp/x86_64-linux-gnu/ports/msgpack/2.0.1/msgpack-2.0.1/msgpack.c: In function 'php_msgpack_unserialize':
/tmp/x86_64-linux-gnu/ports/msgpack/2.0.1/msgpack-2.0.1/msgpack.c:210:29: error: storage size of 'var_hash' isn't known
  msgpack_unserialize_data_t var_hash;
                             ^
make: *** [msgpack.lo] Error 1
/tmp/x86_64-linux-gnu/ports/msgpack/2.0.1/msgpack-2.0.1/msgpack_class.c:20:32: error: field 'var_hash' has incomplete type
     msgpack_unserialize_data_t var_hash;
                                ^
make: *** [msgpack_class.lo] Error 1
========================================================================
```

It seems like @remicollet's fix works ? Is there a reason it hasn't been merged in yet or this issue hasn't been resolved ?

**Comment by sodabrew** [comment]
PR #104 has a fix and is waiting for a project maintainer to review it.

**Comment by aidemingsi** [comment]
/bin/sh /root/package/msgpack-2.0.1/libtool --mode=compile cc  -I. -I/root/package/msgpack-2.0.1 -DPHP_ATOM_INC -I/root/package/msgpack-2.0.1/include -I/root/package/msgpack-2.0.1/main -I/root/package/msgpack-2.0.1 -I/usr/local/php7/include/php -I/usr/local/php7/include/php/main -I/usr/local/php7/include/php/TSRM -I/usr/local/php7/include/php/Zend -I/usr/local/php7/include/php/ext -I/usr/local/php7/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /root/package/msgpack-2.0.1/msgpack.c -o msgpack.lo 
mkdir .libs
 cc -I. -I/root/package/msgpack-2.0.1 -DPHP_ATOM_INC -I/root/package/msgpack-2.0.1/include -I/root/package/msgpack-2.0.1/main -I/root/package/msgpack-2.0.1 -I/usr/local/php7/include/php -I/usr/local/php7/include/php/main -I/usr/local/php7/include/php/TSRM -I/usr/local/php7/include/php/Zend -I/usr/local/php7/include/php/ext -I/usr/local/php7/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /root/package/msgpack-2.0.1/msgpack.c  -fPIC -DPIC -o .libs/msgpack.o
/root/package/msgpack-2.0.1/msgpack.c: In function ‘ps_srlzr_decode_msgpack’:
/root/package/msgpack-2.0.1/msgpack.c:160:29: error: storage size of ‘var_hash’ isn’t known
  msgpack_unserialize_data_t var_hash;
                             ^
/root/package/msgpack-2.0.1/msgpack.c: In function ‘php_msgpack_unserialize’:
/root/package/msgpack-2.0.1/msgpack.c:210:29: error: storage size of ‘var_hash’ isn’t known
  msgpack_unserialize_data_t var_hash;
                             ^
make: *** [msgpack.lo] Error 1

**Comment by Sean-Der** [comment]
This is merged now, master should build with 7.1 now

**Comment by Jan-E** [comment]
Confirmed for PHP 7.0 and 7.1 (x64 TS). The buildbot seems to be busy as well:
http://windows.php.net/downloads/pecl/releases/msgpack/2.0.2/
